const DATA_URL='../data_reports/DATA_REPORT_20260917.md';
const DAILY_REPORT_URL='../reports/2026-09-17/Daily_REPORT_20260917.md';
const pages={summary:'總結',spot:'現貨',global_markets:'重要市場',futures:'期貨',options:'選擇權'};
let current='summary',dailyReport='';
const $=s=>document.querySelector(s);
const esc=v=>v==null||v===''?'—':String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const sec=(title,body)=>`<section class="card"><h3>${esc(title)}</h3>${body}</section>`;
const md=text=>esc(text).replace(/^### (.*)$/gm,'<h4>$1</h4>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h2>$1</h2>').replace(/^\|(.+)\|$/gm,(m)=>`<div class="report-line">${m}</div>`).replace(/\n- /g,'\n• ');
function tabs(){$('#tabs').innerHTML=Object.entries(pages).map(([k,v])=>`<button class="tab" role="tab" aria-selected="${k===current}" data-page="${k}">${v}</button>`).join('');$('#tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{current=b.dataset.page;render()})}
function section(title,patterns){const lines=dailyReport.split('\n');const start=lines.findIndex(x=>patterns.some(p=>x.trim().startsWith(p)));if(start<0)return '';let end=lines.length;for(let i=start+1;i<lines.length;i++){if(/^##\s/.test(lines[i])){end=i;break}}return sec(title,`<pre class="report">${esc(lines.slice(start,end).join('\n'))}</pre>`)}
function render(){tabs();$('#meta').textContent='報告日 2026-09-17｜時區 Asia/Taipei｜來源：DATA_REPORT_20260917 / Daily_REPORT_20260917';let h='';if(current==='summary')h=sec('Daily report',`<pre class="report">${esc(dailyReport)}</pre>`);if(current==='spot')h=section('現貨資料',['## 3. 台股籌碼解讀'])+section('現貨關鍵數據',['## 1. 關鍵數據一覽']);if(current==='global_markets')h=section('重要市場解讀',['## 2. 國際市場解讀'])+section('重要市場關鍵數據',['## 1. 關鍵數據一覽']);if(current==='futures')h=section('期貨解讀',['## 4. 期貨選擇權解讀'])+section('期貨關鍵數據',['## 1. 關鍵數據一覽'])+section('交易計畫',['## 5. 關鍵價位與今日交易計畫']);if(current==='options')h=section('選擇權解讀',['## 4. 期貨選擇權解讀'])+section('選擇權關鍵數據',['## 1. 關鍵數據一覽'])+section('關鍵價位',['## 5. 關鍵價位與今日交易計畫']);$('#app').innerHTML=h||'<section class="card">找不到對應報告段落</section>'}
fetch(DAILY_REPORT_URL).then(r=>{if(!r.ok)throw new Error('Daily report 載入失敗');return r.text()}).then(t=>{dailyReport=t;render()}).catch(e=>{$('#meta').textContent=e.message;$('#app').innerHTML=`<section class="card warning">${esc(e.message)}</section>`});